### ISSUE TITLE
Update main page text

### ISSUE THREAD

**Issue by SeritavdW** [iobis/bioeco-geonode#147]
Title: Welcome to the GOOS BioEco GeoNode
Text: The GOOS BioEco Portal is a publicly available tool for users and data providers to contribute ocean observing programs and  maintain active programs. GeoNode users can explore and compare BioEco portal contributed program detail and metadata. Registered users can upload, edit and manage contributed monitoring program detail including EOVs and EBVs monitored; spatial and temporal information; status of the program; data availability and licences; standardisations; as well as links to tools, outputs and data. This GeoNode is hosted and maintained by the secretariat of the Ocean Biodiversity Information System of the IOC Project Office for IODE.

**Comment by wardappeltans** [comment]
Thanks Serita, I suggest this: 
Text: The GOOS BioEco Portal is a publicly available tool to monitor the status of the marine biological observing system. The GEONODE is the back-end interface where registered users can upload, edit and manage their monitoring program details including which EOVs and EBVs are monitored; spatial and temporal information; status of the program; data availability and licences; standardisation and protocols; as well as links to applications, tools and outputs based on the collected observations. This GeoNode is hosted and maintained by the secretariat of the Ocean Biodiversity Information System (OBIS) based at the IOC Project Office for IODE in Oostende, Belgium as a service to support the Global Ocean Observing System Biology and Ecosystem Panel.

**Comment by SeritavdW** [comment]
Hi Pieter, would you please prioritise this issue so that I have the updated text in the video? Thank you :)
