### ISSUE TITLE
Funding sector options

### ISSUE THREAD

**Issue by SeritavdW** [iobis/bioeco-geonode#152]
Funding sector not allowing multiple options

**Comment by pieterprovoost** [comment]
I'm not able to reproduce this.

<img width="488" alt="Screenshot 2022-07-16 at 11 39 42" src="https://user-images.githubusercontent.com/490041/179349501-d0b760fe-a9e6-47f5-9339-cb8fd26382f6.png">

**Comment by SeritavdW** [comment]
Hi Pieter, I am still not able to select more than one funding sector option?
