### ISSUE TITLE
Metadata field rename

### ISSUE THREAD

**Issue by SeritavdW** [iobis/bioeco-geonode#155]
Field: `GOOS Essential Ocean Variable (EOV) subvariables` rename as `Essential Ocean subvariables (EOV subvariables) & Essential Biodiversity Variables (EBVs)`

Field: `GOOS Essential Ocean Variables (EOVs): Physics, Biochemistry, and Cross-disciplinary` rename as `GOOS Physics, Biochemistry, and Cross-disciplinary EOVs`.

**Comment by pieterprovoost** [comment]
Updated in GeoNode admin.
