### ISSUE TITLE
Field additional info options

### ISSUE THREAD

**Issue by SeritavdW** [iobis/bioeco-geonode#156]
Can we please add "i" or "?" for more info on readiness levels and sub-variables (in the Portal and in GeoNode)? Can we add links in these?

Text for readiness levels:

> The readiness level system is the approach for evaluating new components for possible inclusion in the global ocean observing systems. For more info on the categorisation and description of levels, see the Portal documentation.

Text for sub-variables

> Additional measurements taken/ observations made of the main EOV (BioEco EOV sub-variables, as well as Physics, Biochemistry, and Cross-disciplinary EOVs). For information on see Portal documentation.

**Comment by pieterprovoost** [comment]
This does not appear to be an easy fix, so unlikely to be ready by launch.
