### ISSUE TITLE
Missing regions

### ISSUE THREAD

**Issue by SeritavdW** [iobis/bioeco-geonode#160]
## Network

- Title: Pacific Islands Ocean Observing System (PacIOOS)
- URL: https://geonode.goosocean.org/layers/geonode_data:geonode:PacIOOS

## Problems found
"Hawaii" and some minor outlying Islands are not a selectable terms in 'Regions'. Is it possible to add it, even manually? I will find out the names of the outlying islands mentioned.

**Comment by pieterprovoost** [comment]
Can you try here? https://geonode.goosocean.org/en/admin/base/region/

**Comment by SeritavdW** [comment]
Ah yes,  I will add them.

**Comment by SeritavdW** [comment]
I added Hawaii but still not selectable as an option from the list, does it take a while or do we need to 'refresh' somehow?

**Comment by pieterprovoost** [comment]
@SeritavdW I added it myself now, it was not in the list.

**Comment by SeritavdW** [comment]
I have to reopen this issue because the added regions do not show up in the options from which to choose in the layers

**Comment by pieterprovoost** [comment]
It seems that a restart was needed to make it show up in the layer form: https://geonode.goosocean.org/layers/?limit=5&offset=0&regions__name__in=Hawaii

**Comment by SeritavdW** [comment]
Ah! I see. I added the last 3 regions, if you would please do the restart when you have time. Thank you!

**Comment by pieterprovoost** [comment]
Ok, done.
