### ISSUE TITLE
GeoNode shapefile uploads failing at 30%

### ISSUE THREAD

**Issue by SeritavdW** [iobis/bioeco-geonode#164]

**Comment by SeritavdW** [comment]
[delfini_del_ponente-dolphin_research_project..zip](https://github.com/iobis/bioeco-geonode/files/10498046/delfini_del_ponente-dolphin_research_project.zip)

**Comment by pieterprovoost** [comment]
Neither the filename (underscore versus dash) nor the file structure (fields that did not exist before) match the existing version. Do you still have the original file?

**Comment by SeritavdW** [comment]
No, replacing the files don't work in any way, I tried to upload these as a new layer (not replace an existing), which caused the issue.

**Comment by pieterprovoost** [comment]
```
e HTTP/1.1" 200 146 "https://geonode.goosocean.org/layers/upload" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
db4geonode       | 2023-01-25 13:57:34.131 UTC [1160] ERROR:  relation "gt_pk_metadata" does not exist at character 15
db4geonode       | 2023-01-25 13:57:34.131 UTC [1160] STATEMENT:  SELECT * FROM GT_PK_METADATA WHERE 1 = 0
```

Creating the table removes the error but does not resolve the issue:

```
CREATE TABLE public.gt_pk_metadata (
  table_schema VARCHAR(32) NOT NULL,
  table_name VARCHAR(32) NOT NULL,
  pk_column VARCHAR(32) NOT NULL,
  pk_column_idx INTEGER,
  pk_policy VARCHAR(32),
  pk_sequence VARCHAR(64),
  unique (table_schema, table_name, pk_column),
  check (pk_policy in ('sequence', 'assigned', 'autogenerated'))
)
```

**Comment by pieterprovoost** [comment]
Solved for now by rolling back to 3 days old version

**Comment by pieterprovoost** [comment]
Issue came back after a system update and container rebuild. To test:

- [x] Restart -> OK
- [x] Django container rebuild only -> FAIL
- [x] Django container rebuild only (`docker-compose.development.yml`) -> OK
- [ ] https://github.com/GeoNode/geonode/issues/8436
- [x] Prune and all containers rebuild -> FAIL (GeoServer restart loop)
- [x] System update only -> OK
